### ISSUE TITLE
Systemd configuration files incorrect

### ISSUE THREAD

**Issue by ioqy** [Jamesits/pve-fake-subscription#9] opened 2022-12-13 10:07 UTC
1.  The file `/lib/systemd/system/pve-fake-subscription.timer.service` is wrong and just a copy of `/lib/systemd/system/pve-fake-subscription.timer`
2. The other two systemd files have permissions that systemd doesn't like and it writes warning messages into the journal sometimes (for instance after `systemctl daemon-reload`):
```
Dec 13 10:51:58 pve systemd[1]: Configuration file /lib/systemd/system/pve-fake-subscription.timer is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 13 10:51:58 pve systemd[1]: Configuration file /lib/systemd/system/pve-fake-subscription.timer is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
Dec 13 10:51:58 pve systemd[1]: Configuration file /lib/systemd/system/pve-fake-subscription.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Dec 13 10:51:58 pve systemd[1]: Configuration file /lib/systemd/system/pve-fake-subscription.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
```

**Comment by Jamesits** [comment] 2022-12-13 14:16
duplicate of #3

**Comment by Jamesits** [comment] 2022-12-19 09:27
File permission should be fixed in the latest release.

**Closed by Jamesits** 2022-12-19 09:27 UTC
Labels: duplicate
